package com.example.demo;

/**
 * Created by mingyama on 4/5/18.
 */

import com.example.demo.model.Member;
import com.example.demo.repos.MemberRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;

import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

/**
 * Created by mingyama on 4/4/18.
 */


@Controller    // This means that this class is a Controller
@RequestMapping(path="/demo") // This means URL's start with /demo (after Application path)
public class DemoController {
    @Autowired // This means to get the bean called memberRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private MemberRepository memberRepository;


    @GetMapping(path="/add") // Map ONLY GET Requests
    public @ResponseBody String addNewUser (@RequestParam String name
            , @RequestParam String email) {
        // @ResponseBody means the returned String is the response, not a view name
        // @RequestParam means it is a parameter from the GET or POST request

        Member member = new Member();
        String[] parts = name.split(name);

        String firstName = parts.length >= 1 ? parts[0] : null;
        String lastName = parts.length >= 2 ? parts[1] : null;
        member.setFirstName(firstName);
        member.setLastName(lastName);

        member.setEmail(email);
        memberRepository.save(member);
        return "Saved";
    }

    @GetMapping(path="/all")
    public @ResponseBody Iterable<Member> getAllUsers() {
        // This returns a JSON or XML with the users
        return memberRepository.findAll();
    }

    @GetMapping(path = "/error")
    public @ResponseBody String error() {
        return "error";
    }
}

